
import React from 'react';
import type { SelectableCountry, ComparisonCategory } from './types';

// This list now includes specific requests (North Macedonia, UAE) and top global expat destinations.
// Sorted alphabetically.
export const SELECTABLE_COUNTRIES: SelectableCountry[] = [
  { code: 'AL', name: 'Albania', currency: 'ALL' },
  { code: 'AU', name: 'Australia', currency: 'AUD' },
  { code: 'AT', name: 'Austria', currency: 'EUR' },
  { code: 'BE', name: 'Belgium', currency: 'EUR' },
  { code: 'BA', name: 'Bosnia and Herzegovina', currency: 'BAM' },
  { code: 'BR', name: 'Brazil', currency: 'BRL' },
  { code: 'BG', name: 'Bulgaria', currency: 'BGN' },
  { code: 'CA', name: 'Canada', currency: 'CAD' },
  { code: 'CN', name: 'China', currency: 'CNY' },
  { code: 'HR', name: 'Croatia', currency: 'EUR' },
  { code: 'CY', name: 'Cyprus', currency: 'EUR' },
  { code: 'CZ', name: 'Czechia', currency: 'CZK' },
  { code: 'DK', name: 'Denmark', currency: 'DKK' },
  { code: 'EE', name: 'Estonia', currency: 'EUR' },
  { code: 'FI', name: 'Finland', currency: 'EUR' },
  { code: 'FR', name: 'France', currency: 'EUR' },
  { code: 'DE', name: 'Germany', currency: 'EUR' },
  { code: 'GR', name: 'Greece', currency: 'EUR' },
  { code: 'HU', name: 'Hungary', currency: 'HUF' },
  { code: 'IS', name: 'Iceland', currency: 'ISK' },
  { code: 'IE', name: 'Ireland', currency: 'EUR' },
  { code: 'IT', name: 'Italy', currency: 'EUR' },
  { code: 'JP', name: 'Japan', currency: 'JPY' },
  { code: 'LV', name: 'Latvia', currency: 'EUR' },
  { code: 'LT', name: 'Lithuania', currency: 'EUR' },
  { code: 'LU', name: 'Luxembourg', currency: 'EUR' },
  { code: 'MT', name: 'Malta', currency: 'EUR' },
  { code: 'MX', name: 'Mexico', currency: 'MXN' },
  { code: 'ME', name: 'Montenegro', currency: 'EUR' },
  { code: 'NL', name: 'Netherlands', currency: 'EUR' },
  { code: 'NZ', name: 'New Zealand', currency: 'NZD' },
  { code: 'MK', name: 'North Macedonia', currency: 'MKD' },
  { code: 'NO', name: 'Norway', currency: 'NOK' },
  { code: 'PL', name: 'Poland', currency: 'PLN' },
  { code: 'PT', name: 'Portugal', currency: 'EUR' },
  { code: 'RO', name: 'Romania', currency: 'RON' },
  { code: 'RS', name: 'Serbia', currency: 'RSD' },
  { code: 'SG', name: 'Singapore', currency: 'SGD' },
  { code: 'SK', name: 'Slovakia', currency: 'EUR' },
  { code: 'SI', name: 'Slovenia', currency: 'EUR' },
  { code: 'ES', name: 'Spain', currency: 'EUR' },
  { code: 'SE', name: 'Sweden', currency: 'SEK' },
  { code: 'CH', name: 'Switzerland', currency: 'CHF' },
  { code: 'TH', name: 'Thailand', currency: 'THB' },
  { code: 'TR', name: 'Türkiye', currency: 'TRY' },
  { code: 'AE', name: 'United Arab Emirates', currency: 'AED' },
  { code: 'GB', name: 'United Kingdom', currency: 'GBP' },
  { code: 'US', name: 'United States', currency: 'USD' },
].sort((a, b) => a.name.localeCompare(b.name));

export const CATEGORIES: ComparisonCategory[] = [
    { id: 'food', name: 'Food & Non-alcoholic Beverages', icon: <span className="text-3xl">🍽️</span> },
    { id: 'alcohol-beverages', name: 'Alcoholic Beverages & Tobacco', icon: <span className="text-3xl">🍷</span> },
    { id: 'clothing', name: 'Clothing & Footwear', icon: <span className="text-3xl">👕</span> },
    { id: 'housing', name: 'Housing & Utilities', icon: <span className="text-3xl">🏠</span> },
    { id: 'furnishings', name: 'Furnishings & Household Equipment', icon: <span className="text-3xl">🛋️</span> },
    { id: 'health', name: 'Health', icon: <span className="text-3xl">⚕️</span> },
    { id: 'transport', name: 'Transport', icon: <span className="text-3xl">🚆</span> },
    { id: 'communication', name: 'Communication', icon: <span className="text-3xl">📡</span> },
    { id: 'recreation-culture', name: 'Recreation & Culture', icon: <span className="text-3xl">🏖️</span> },
    { id: 'education', name: 'Education', icon: <span className="text-3xl">🎓</span> },
    { id: 'restaurants', name: 'Restaurants & Hotels', icon: <span className="text-3xl">🍜</span> },
    { id: 'total', name: 'TOTAL (All Products)', icon: <span className="text-3xl">🛒</span> },
];
